
title: Cfisha27 space
description: (^q^) >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ghiotino.github.io/cfisha27.github.io/"
twitter_username: cfisha27
github_username:  Ghiotino

# Build settings
theme: minima
plugins:
  - jekyll-feed

